language: ruby
rvm:
  - 2.6.3
script:
  - bundle exec rake test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false
cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
before_install:
  - gem update --system
  - gem install bundler
